name: Build Widget

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Build widget
        run: npm run build

      - name: Update dist folder
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist
          git commit -m "Update dist build" || echo "No changes"
          git push
